### Listar filmes
GET http://localhost:3000/filmes

### Criar um novo filme
POST http://localhost:3000/filmes
Content-Type: application/json

{
  "titulo": "Bob Marley - Rebel Music",
  "diretor": "Kevin Macdonald",
  "genero": "Documentário",
  "ano": 2012,
  "duracao": 144,
  "classificacao": 16
}

### Atualizar um filme
PUT http://localhost:3000/filmes/a3ed7dcd-4302-46db-85f8-239ef786496e
Content-Type: application/json

{
  "id": 1,
  "titulo": "Ainda estou aqui",
  "diretor": "Casey Affleck",
  "genero": "Drama",
  "ano": 2010,
  "duracao": 118,
  "classificacao": 16
}

### Atualizar parcialmente um filme
PATCH http://localhost:3000/filmes/a3ed7dcd-4302-46db-85f8-239ef786496e
Content-Type: application/json

{
  "duracao": 108
}


### Deletar um filme
DELETE http://localhost:3000/filmes/8ea04e84-2313-428e-9a17-4ca4f44f8370
Content-Type: application/json

{
  "id": 1
}